[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

# Ignore flat-layout.
[tool.setuptools]
py-modules = []

[project]
name = "pybuildingenergy"
version = "1.0.5"
description = "Energy Simulation of building usin ISO52016 and more"
license = {file = "LICENSE.md"}
readme = "README.md"
requires-python = ">=3.8.0"
authors = [{name = "Daniele Antonucci", email = "daniele.antonucci@eurac.edu"}]
maintainers = [{name = "Daniele Antonucci", email = "daniele.antonucci@eurac.edu"}]
keywords = [
    "energy",
    "building",
    "heating and cooling",
    "52016",
    "EPBD",
]
dependencies = [
    "bump2version==0.5.11",
    "coverage==4.5.4", 
    "pandas>=2.0.3",
    "numpy==1.23.2",
    "DateTime==5.1", 
    "timezonefinder==6.2.0",
    "requests==2.31.0",
    "tqdm==4.66.1",
    "Pyarrow==13.0.0",
    "pyecharts == 2.0.4",
    "geopy==2.4.1",
    "tqdm==4.66.1",
    "pvlib==0.10.1",
    "scikit-learn==1.4.1.post1",
    "urllib3==1.26.18",
    "requests>=2.0"
]


